// Translations for multilingual support
const translations = {
    // English translations
    en: {
      // Header
      memoryGame: "Memory Game",
      logout: "Logout",
      noNotifications: "No new notifications",
  
      // Navigation
      home: "Home",
      competitions: "Competitions",
      results: "Results",
      iqTest: "IQ Test",
      profile: "Profile",
      report: "Report a Problem",
  
      // Competition details
      back: "Back to Competitions",
      available: "Available",
      upcoming: "Upcoming",
      closed: "Closed",
      description: "Description",
      memoryDescExtended:
        "Train your memory and beat the competition in our exciting Memory Game challenge. Participants will test their short-term memory capacity, recall speed, and pattern recognition abilities through a series of increasingly difficult memory tasks. Can you remember more than your competitors?",
      registration: "Registration",
      open: "Open",
      requiredGrade: "Required IQ Test Grade",
      startDate: "Start Date",
      location: "Location",
      locationValue: "Online",
      gender: "Gender",
      allGenders: "All",
      gameType: "Game Type",
      individual: "Individual",
      timeLimit: "Time Limit",
      difficulty: "Difficulty",
      awards: "Awards",
      firstPrize: "1st Place: 50000DA + Gold Medal",
      secondPrize: "2nd Place: 25000DA + Silver Medal",
      thirdPrize: "3rd Place: 10000DA + Bronze Medal",
      certificates: "Certificates for all participants",
      rules: "Rules",
      rule1: "Participants must complete all memory challenges within the time limit",
      rule2: "No external aids or memory techniques using physical tools are allowed",
      rule3: "Each level must be completed before proceeding to the next",
      rule4: "Points are awarded based on accuracy, speed, and difficulty level completed",
      rule5: "Judges' decisions are final",
      gamePreview: "Game Preview",
      previewText: "Click on the cards to see a preview of the memory game!",
      startsIn: "Starts in:",
      days: "Days",
      hours: "Hours",
      minutes: "Minutes",
      seconds: "Seconds",
      registerNow: "Register Now",
      matchFound: "Match found!",
      tryAgain: "Try again!",
      allMatched: "All pairs matched! Great job!",
    },
  
    // Arabic translations
    ar: {
      // Header
      memoryGame: "لعبة الذاكرة",
      logout: "تسجيل الخروج",
      noNotifications: "لا توجد إشعارات جديدة",
  
      // Navigation
      home: "الرئيسية",
      competitions: "المسابقات",
      results: "النتائج",
      iqTest: "اختبار الذكاء",
      profile: "الملف الشخصي",
      report: "الإبلاغ عن مشكلة",
  
      // Competition details
      back: "العودة إلى المسابقات",
      available: "متاح",
      upcoming: "قادم",
      closed: "مغلق",
      description: "الوصف",
      memoryDescExtended:
        "درب ذاكرتك وتفوق على المنافسة في تحدي لعبة الذاكرة المثير. سيختبر المشاركون قدرة الذاكرة قصيرة المدى، وسرعة الاسترجاع، وقدرات التعرف على الأنماط من خلال سلسلة من مهام الذاكرة المتزايدة الصعوبة. هل يمكنك تذكر أكثر من منافسيك؟",
      registration: "التسجيل",
      open: "مفتوح",
      requiredGrade: "درجة اختبار الذكاء المطلوبة",
      startDate: "تاريخ البدء",
      location: "الموقع",
      locationValue: "عبر الإنترنت",
      gender: "الجنس",
      allGenders: "الكل",
      gameType: "نوع اللعبة",
      individual: "فردي",
      timeLimit: "الحد الزمني",
      difficulty: "الصعوبة",
      awards: "الجوائز",
      firstPrize: "المركز الأول: 50000 دج + ميدالية ذهبية",
      secondPrize: "المركز الثاني: 25000 دج + ميدالية فضية",
      thirdPrize: "المركز الثالث: 10000 دج + ميدالية برونزية",
      certificates: "شهادات لجميع المشاركين",
      rules: "القواعد",
      rule1: "يجب على المشاركين إكمال جميع تحديات الذاكرة ضمن الحد الزمني",
      rule2: "لا يسمح باستخدام المساعدات الخارجية أو تقنيات الذاكرة باستخدام أدوات مادية",
      rule3: "يجب إكمال كل مستوى قبل الانتقال إلى المستوى التالي",
      rule4: "يتم منح النقاط بناءً على الدقة والسرعة ومستوى الصعوبة المكتمل",
      rule5: "قرارات الحكام نهائية",
      gamePreview: "معاينة اللعبة",
      previewText: "انقر على البطاقات لمشاهدة معاينة للعبة الذاكرة!",
      startsIn: "يبدأ في:",
      days: "أيام",
      hours: "ساعات",
      minutes: "دقائق",
      seconds: "ثواني",
      registerNow: "سجل الآن",
      matchFound: "تم العثور على تطابق!",
      tryAgain: "حاول مرة أخرى!",
      allMatched: "تم مطابقة جميع الأزواج! عمل رائع!",
    },
  }
  